# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rajni.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.bg_1 = QtWidgets.QLabel(self.centralwidget)
        self.bg_1.setGeometry(QtCore.QRect(0, 0, 900, 720))
        self.bg_1.setText("")
        self.bg_1.setPixmap(QtGui.QPixmap("../MidiProjectGIFS/2416004.webp"))
        self.bg_1.setScaledContents(True)
        self.bg_1.setObjectName("bg_1")
        self.bg_3 = QtWidgets.QLabel(self.centralwidget)
        self.bg_3.setGeometry(QtCore.QRect(40, 30, 461, 391))
        self.bg_3.setStyleSheet("\n"
"background-color: rgb(47, 47, 47);\n"
"")
        self.bg_3.setText("")
        self.bg_3.setObjectName("bg_3")
        self.bg_2 = QtWidgets.QLabel(self.centralwidget)
        self.bg_2.setGeometry(QtCore.QRect(510, 30, 351, 271))
        self.bg_2.setStyleSheet("\n"
"background-color: rgb(44, 44, 44);")
        self.bg_2.setText("")
        self.bg_2.setObjectName("bg_2")
        self.gif_1 = QtWidgets.QLabel(self.centralwidget)
        self.gif_1.setGeometry(QtCore.QRect(50, 40, 441, 371))
        self.gif_1.setText("")
        self.gif_1.setPixmap(QtGui.QPixmap("../MidiProjectGIFS/walk-loop.gif"))
        self.gif_1.setScaledContents(True)
        self.gif_1.setObjectName("gif_1")
        self.gif_2 = QtWidgets.QLabel(self.centralwidget)
        self.gif_2.setGeometry(QtCore.QRect(520, 40, 331, 251))
        self.gif_2.setStyleSheet("")
        self.gif_2.setText("")
        self.gif_2.setPixmap(QtGui.QPixmap("../MidiProjectGIFS/5ac3659684140aa60ceca491b48b8bb2.gif"))
        self.gif_2.setScaledContents(True)
        self.gif_2.setObjectName("gif_2")
        self.bg_4 = QtWidgets.QLabel(self.centralwidget)
        self.bg_4.setGeometry(QtCore.QRect(510, 310, 351, 181))
        self.bg_4.setStyleSheet("background-color: rgb(45, 45, 45);")
        self.bg_4.setText("")
        self.bg_4.setScaledContents(False)
        self.bg_4.setObjectName("bg_4")
        self.gif_3 = QtWidgets.QLabel(self.centralwidget)
        self.gif_3.setGeometry(QtCore.QRect(520, 320, 331, 161))
        self.gif_3.setText("")
        self.gif_3.setPixmap(QtGui.QPixmap("../MidiProjectGIFS/Intercept_Echo_v2-3.5MB-2-1542062294.gif"))
        self.gif_3.setScaledContents(True)
        self.gif_3.setObjectName("gif_3")
        self.bg_5 = QtWidgets.QLabel(self.centralwidget)
        self.bg_5.setGeometry(QtCore.QRect(40, 430, 461, 61))
        self.bg_5.setStyleSheet("background-color: rgb(43, 43, 43);")
        self.bg_5.setText("")
        self.bg_5.setObjectName("bg_5")
        self.gif_4 = QtWidgets.QLabel(self.centralwidget)
        self.gif_4.setGeometry(QtCore.QRect(50, 439, 441, 41))
        self.gif_4.setText("")
        self.gif_4.setPixmap(QtGui.QPixmap("../MidiProjectGIFS/result (1).gif"))
        self.gif_4.setScaledContents(True)
        self.gif_4.setObjectName("gif_4")
        self.text_time = QtWidgets.QTextBrowser(self.centralwidget)
        self.text_time.setGeometry(QtCore.QRect(40, 540, 221, 101))
        self.text_time.setStyleSheet("background-color: transparent;\n"
"")
        self.text_time.setObjectName("text_time")
        self.text_day = QtWidgets.QTextBrowser(self.centralwidget)
        self.text_day.setGeometry(QtCore.QRect(270, 540, 221, 101))
        self.text_day.setStyleSheet("background-color: transparent;\n"
"")
        self.text_day.setObjectName("text_day")
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(670, 530, 111, 91))
        self.exit.setStyleSheet("background-color:Transparent;")
        self.exit.setText("")
        self.exit.setObjectName("exit")
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(550, 530, 101, 91))
        self.start.setStyleSheet("background-color:Transparent;")
        self.start.setText("")
        self.start.setObjectName("start")
        self.bg_6 = QtWidgets.QLabel(self.centralwidget)
        self.bg_6.setGeometry(QtCore.QRect(546, 532, 111, 91))
        self.bg_6.setStyleSheet("")
        self.bg_6.setText("")
        self.bg_6.setPixmap(QtGui.QPixmap("../MidiProjectGIFS/pngtree-3d-microphone-record-icon-png-image_2941940-removebg-preview.png"))
        self.bg_6.setScaledContents(True)
        self.bg_6.setObjectName("bg_6")
        self.bg_7 = QtWidgets.QLabel(self.centralwidget)
        self.bg_7.setGeometry(QtCore.QRect(680, 540, 91, 71))
        self.bg_7.setText("")
        self.bg_7.setPixmap(QtGui.QPixmap("../MidiProjectGIFS/images-removebg-preview.png"))
        self.bg_7.setScaledContents(True)
        self.bg_7.setObjectName("bg_7")
        self.bg_1.raise_()
        self.bg_3.raise_()
        self.bg_2.raise_()
        self.gif_1.raise_()
        self.gif_2.raise_()
        self.bg_4.raise_()
        self.gif_3.raise_()
        self.bg_5.raise_()
        self.gif_4.raise_()
        self.text_time.raise_()
        self.text_day.raise_()
        self.bg_6.raise_()
        self.bg_7.raise_()
        self.exit.raise_()
        self.start.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
